/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HISTORY_H_RPCGEN
#define _HISTORY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct event {
	char id[3];
	char month[3];
	char date[3];
	char desc[1000];
};
typedef struct event event;

#define HISTORY_EVENTS 0x33317452
#define HISTORY_EVENTS_ADD 1

#if defined(__STDC__) || defined(__cplusplus)
#define Add 1
extern  event * add_1(event *, CLIENT *);
extern  event * add_1_svc(event *, struct svc_req *);
extern int history_events_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Add 1
extern  event * add_1();
extern  event * add_1_svc();
extern int history_events_1_freeresult ();
#endif /* K&R C */
#define HISTORY_EVENTS_QUERY 2

#if defined(__STDC__) || defined(__cplusplus)
#define Query 1
extern  event * query_2(event *, CLIENT *);
extern  event * query_2_svc(event *, struct svc_req *);
extern int history_events_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Query 1
extern  event * query_2();
extern  event * query_2_svc();
extern int history_events_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_event (XDR *, event*);

#else /* K&R C */
extern bool_t xdr_event ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HISTORY_H_RPCGEN */
