/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "history.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

event *
add_1(event *argp, CLIENT *clnt)
{
	static event clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Add,
		(xdrproc_t) xdr_event, (caddr_t) argp,
		(xdrproc_t) xdr_event, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

event *
query_2(event *argp, CLIENT *clnt)
{
	static event clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Query,
		(xdrproc_t) xdr_event, (caddr_t) argp,
		(xdrproc_t) xdr_event, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
