/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "history.h"
#include <stdio.h>
#include <stdlib.h>

void
history_events_1(char *host,char *date,char *month,char *record)
{
	CLIENT *clnt;
	event  NewEvent, *ResultedEvent;
	int i=0;

#ifndef	DEBUG
	clnt = clnt_create (host, HISTORY_EVENTS, HISTORY_EVENTS_ADD, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/*NewEvent.date = date;
	NewEvent.month = month;*/
	for(i = 0; i<strlen(date);i++)
		NewEvent.date[i] = date[i];
		NewEvent.date[strlen(date)]='\0';
	for(i = 0; i<strlen(month);i++)
		NewEvent.month[i] = month[i];
		NewEvent.month[strlen(month)]='\0';
	/*NewEvent.desc = record;*/
	for(i = 0; i<strlen(record);i++)
		NewEvent.desc[i] = record[i];
		NewEvent.desc[strlen(record)]='\0';
	ResultedEvent = add_1(&NewEvent, clnt);
	if (ResultedEvent == (event *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf(" \n Event Successfully Added : %s \n", ResultedEvent->desc);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
history_events_2(char *host,char *date,char *month)
{
	CLIENT *clnt;
	event  SearchEvent, *ResultedEvent;
	int i=0, search_results = 0;

#ifndef	DEBUG
	clnt = clnt_create (host, HISTORY_EVENTS, HISTORY_EVENTS_QUERY, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/*SearchEvent.date = date;
	SearchEvent.month = month;*/
	for(i = 0; i<strlen(date);i++)
		SearchEvent.date[i] = date[i];
		SearchEvent.date[strlen(date)]='\0';
	for(i = 0; i<strlen(month);i++)
		SearchEvent.month[i] = month[i];
		SearchEvent.month[strlen(month)]='\0';
	ResultedEvent = query_2(&SearchEvent, clnt);
	if (ResultedEvent == (event *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		if(strlen(ResultedEvent->desc)==0)
		{
			printf("\n  No Records Found \n");
		}
		else
		{
			printf("\n Records Found: \n");
			printf("\n %s \n",ResultedEvent->desc);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host, *date, *month, *record;

	if (argc < 4) {
		printf ("usage: %s server_host operation month date event\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	date = argv[3];
	month = argv[4];
	if(!strcmp(argv[2],"add"))
	{
		record = argv[5];
		history_events_1(host,date,month,record);
	}
	else if(!strcmp(argv[2],"query"))
	{
		history_events_2(host,date,month);
	}
	else
	 	printf("\n Please provide either add of query\n");

	exit (0);
}
