/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "history.h"
#include <stdio.h>
#include <stdlib.h>

event *
add_1_svc(event *argp, struct svc_req *rqstp)
{
	static event result;
	FILE *fp;
	char history[1500];
     	strcpy(history,argp->date);
	 strcat(history,"\t");
	 strcat(history,argp->month);
	 strcat(history,"\t");
	 strcat(history,argp->desc);
	 fp = fopen("history.txt","a");
	 fprintf(fp,"\n%s",history);
	 fclose(fp);
	 strcpy(result.desc,history);
	 return &result;
}

event *
query_2_svc(event *argp, struct svc_req *rqstp)
{
	static event result;
	char history[100];
	FILE *fp;
   	char * line = NULL;
    	size_t len = 0;
    	ssize_t read;
	result.desc[0]='\0';
    	strcpy(history,argp->date);
	strcat(history,"\t");
	strcat(history,argp->month);
    	fp = fopen("history.txt", "r");
	while ((read = getline(&line, &len, fp)) != -1) {
        if ( strstr(line, history) ){
                printf("%s\n", line);
                strcat(result.desc,line);
            }
    	}
    	fclose(fp);
	return &result;
}
